version: '3.3'

services:

  db:
    container_name: ${DB_NAME}
    image: mysql:5.7
    volumes:
      - ./database-files:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306

  phpmyadmin:
    container_name: ${PMA_NAME}
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_HOST_PORT}:80

  wordpress:
    container_name: ${WP_NAME}
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - ${WORDPRESS_HOST_PORT}:80
      - 443:443
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: ${MYSQL_USER}
       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wordpress-files:/var/www/html
      - ./upload.ini:/usr/local/etc/php/conf.d/uploads.ini
